# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "music_xray_api"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jeff durand"]
  s.date = "2012-05-02"
  s.description = "wrapper for music xray api "
  s.email = "jeff.durand@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/music_xray_api.rb",
    "lib/music_xray_api/base.rb",
    "lib/music_xray_api/track.rb",
    "lib/music_xray_api/track_match_request.rb",
    "lib/music_xray_api/track_set.rb",
    "lib/music_xray_api/track_set_member.rb",
    "music_xray_api.gemspec",
    "test/helper.rb",
    "test/test_music_xray_api.rb"
  ]
  s.homepage = "http://github.com/johnnyiller/Music-Xray-Api-Wrapper"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Interface with the music xray api"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
    else
      s.add_dependency(%q<xml-simple>, [">= 0"])
    end
  else
    s.add_dependency(%q<xml-simple>, [">= 0"])
  end
end

