# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{music_xray_api}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jeff durand"]
  s.date = %q{2012-11-13}
  s.description = %q{wrapper for music xray api }
  s.email = %q{jeff.durand@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/music_xray_api.rb",
     "lib/music_xray_api/base.rb",
     "lib/music_xray_api/track.rb",
     "lib/music_xray_api/track_match_request.rb",
     "lib/music_xray_api/track_set.rb",
     "lib/music_xray_api/track_set_member.rb",
     "music_xray_api.gemspec",
     "test/helper.rb",
     "test/test_music_xray_api.rb"
  ]
  s.homepage = %q{http://github.com/johnnyiller/Music-Xray-Api-Wrapper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Interface with the music xray api}
  s.test_files = [
    "test/helper.rb",
     "test/test_music_xray_api.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
    else
      s.add_dependency(%q<xml-simple>, [">= 0"])
    end
  else
    s.add_dependency(%q<xml-simple>, [">= 0"])
  end
end

